### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by bryannorton** [Alexqw/xbmc-gamepass#254]
I'm running Kodi on a Mac Mini, but am having this issue on an Amazon FireTV and Amazon Fire Stick as well.  The add on worked fine last season, but this season, when I launch it, it says "Unexpected Error." and asks me to enable debugging, and submit a bug report.  I've attached my kodi.log file, but didn't now where the addons debug file was located.  I did enable debug mode, attempted to launch the app, then disabled debug, but I don't know where on a Mac I could get that debug file.  
[kodi.log.txt](https://github.com/Alexqw/xbmc-gamepass/files/416357/kodi.log.txt)

**Comment by Alexqw** [comment]
@bryannorton You're running into this Python bug: #183 
I'm a bit surprised, as I thought most of the platforms and builds had been updated by now. I know Kodi Krypton uses a new enough python, though I do expect a lot of breaking with Krypton as it continues to develop, so I'm not sure I'd recommend it for daily usage...

Maybe Game Pass snuck in a new redirect and that's why you're seeing this...

---Alex

**Comment by bryannorton** [comment]
Agreed, I won't be using Krypton until a stable final release.  I'm using 16.1 now. 

Here's some strangeness...I messed around with downgrading the GP add on to one I had in cache (0.8.1, I think) and it started up, but wouldn't play anything (got a bad JuJu <sic> error).  I then upgraded to 0.9.0, and it played, but didn't show any 2016 games.  I then upgraded to the current 0.9.1...and it works.  Well, it worked on my two Amazon Fire devices, but not my Mac Mini.

**Comment by Alexqw** [comment]
@bryannorton Game Pass change's their URLs and server responses from time to time, so old versions of the app no longer work. So, I'm not surprised that the latest version of the addon works best. ;-)

---Alex

**Comment by bryannorton** [comment]
Sure, makes sense, but what does surprise me is doing that downgrade, followed by an upgrade, fixed the problem on two out of three boxes.  Unfortunately, the box I use the most is the one it didn't fix.  Any ideas why the addon would have a problem in Jarvis on some boxes and not others?  Would the addon debug log (as opposed to just the Kodi one) help?   If so, let me know where to find it on a Mac, and I'll post. Thanks for your help!

**Comment by Alexqw** [comment]
@bryannorton The downgrade upgrade shouldn't have changed anything, so I can't speak to that.

As for why some machines work and some don't, is because of differing versions of Python (as indicated in the bug I linked to earlier). On some platforms, Kodi uses the version of python provided by the OS, on other platforms it is bundled, and they bundle a different version of python on different platforms. Yay for complexity.

Thankfully, it sounds like they've /really/ cleaned this up with Krypton. So it should be much more sane in the future.

The bug you're encountering is a bug in Python itself and was fixed in 2.7.9.

---Alex

**Comment by bryannorton** [comment]
Ok, thanks...so maybe downgrading to 16.0 (what I was running last season when it worked fine) might fix the issue.  I'll try that.  If not, I'll wait for Krytpon stable.  Thanks for your help

**Comment by Alexqw** [comment]
@bryannorton Sounds good. Closing. :-)

---Alex

**Comment by bryannorton** [comment]
For what it's worth...upgrading to Krypton fixed the problem.  I'll try this out and hopefully it won't be too buggy to keep using

**Comment by bryannorton** [comment]
And, after downgrading back to 16.1, it works.  Weird.  I downgraded to 15.2, then 16.0, and it never worked.  Returned to 16.1, still broken.  I upgraded to 17.0 A3, and it worked.  I then downgraded to 16.1, and it started working.
